/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminAtividadesRouteImport } from './routes/admin.atividades'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCustosRouteImport } from './routes/admin.custos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as ClienteContratosRouteImport } from './routes/cliente.contratos'
import { Route as ClienteDocumentosRouteImport } from './routes/cliente.documentos'
import { Route as ClienteEventosRouteImport } from './routes/cliente.eventos'
import { Route as ClienteOrcamentosRouteImport } from './routes/cliente.orcamentos'
import { Route as ClientePagamentosRouteImport } from './routes/cliente.pagamentos'
import { Route as ClientePerfilRouteImport } from './routes/cliente.perfil'
import { Route as AdminClientesIndexRouteImport } from './routes/admin.clientes.index'
import { Route as AdminClientesIdRouteImport } from './routes/admin.clientes.$id'
import { Route as AdminClientesNovoRouteImport } from './routes/admin.clientes.novo'
import { Route as AdminContratosIndexRouteImport } from './routes/admin.contratos.index'
import { Route as AdminContratosIdRouteImport } from './routes/admin.contratos.$id'
import { Route as AdminEventosIndexRouteImport } from './routes/admin.eventos.index'
import { Route as AdminEventosIdRouteImport } from './routes/admin.eventos.$id'
import { Route as AdminEventosNovoRouteImport } from './routes/admin.eventos.novo'
import { Route as AdminOrcamentosIndexRouteImport } from './routes/admin.orcamentos.index'
import { Route as AdminOrcamentosIdRouteImport } from './routes/admin.orcamentos.$id'
import { Route as AdminOrcamentosNovoRouteImport } from './routes/admin.orcamentos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtividadesRoute = AdminAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustosRoute = AdminCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteContratosRoute = ClienteContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteDocumentosRoute = ClienteDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteEventosRoute = ClienteEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteOrcamentosRoute = ClienteOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePagamentosRoute = ClientePagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesNovoRoute = AdminClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosIndexRoute = AdminContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosIdRoute = AdminContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosIndexRoute = AdminEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosIdRoute = AdminEventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosNovoRoute = AdminEventosNovoRouteImport.update({
  id: '/eventos/novo',
  path: '/eventos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosIndexRoute = AdminOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosIdRoute = AdminOrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosNovoRoute = AdminOrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/custos': typeof AdminCustosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/cliente/contratos': typeof ClienteContratosRoute
  '/cliente/documentos': typeof ClienteDocumentosRoute
  '/cliente/eventos': typeof ClienteEventosRoute
  '/cliente/orcamentos': typeof ClienteOrcamentosRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/clientes/novo': typeof AdminClientesNovoRoute
  '/admin/contratos/$id': typeof AdminContratosIdRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
  '/admin/eventos/novo': typeof AdminEventosNovoRoute
  '/admin/orcamentos/$id': typeof AdminOrcamentosIdRoute
  '/admin/orcamentos/novo': typeof AdminOrcamentosNovoRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/orcamentos/': typeof AdminOrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/custos': typeof AdminCustosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/cliente/contratos': typeof ClienteContratosRoute
  '/cliente/documentos': typeof ClienteDocumentosRoute
  '/cliente/eventos': typeof ClienteEventosRoute
  '/cliente/orcamentos': typeof ClienteOrcamentosRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/clientes/novo': typeof AdminClientesNovoRoute
  '/admin/contratos/$id': typeof AdminContratosIdRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
  '/admin/eventos/novo': typeof AdminEventosNovoRoute
  '/admin/orcamentos/$id': typeof AdminOrcamentosIdRoute
  '/admin/orcamentos/novo': typeof AdminOrcamentosNovoRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/contratos': typeof AdminContratosIndexRoute
  '/admin/eventos': typeof AdminEventosIndexRoute
  '/admin/orcamentos': typeof AdminOrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/custos': typeof AdminCustosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/cliente/contratos': typeof ClienteContratosRoute
  '/cliente/documentos': typeof ClienteDocumentosRoute
  '/cliente/eventos': typeof ClienteEventosRoute
  '/cliente/orcamentos': typeof ClienteOrcamentosRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/clientes/novo': typeof AdminClientesNovoRoute
  '/admin/contratos/$id': typeof AdminContratosIdRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
  '/admin/eventos/novo': typeof AdminEventosNovoRoute
  '/admin/orcamentos/$id': typeof AdminOrcamentosIdRoute
  '/admin/orcamentos/novo': typeof AdminOrcamentosNovoRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/orcamentos/': typeof AdminOrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cliente'
    | '/admin/agenda'
    | '/admin/atividades'
    | '/admin/configuracoes'
    | '/admin/custos'
    | '/admin/financeiro'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/cliente/contratos'
    | '/cliente/documentos'
    | '/cliente/eventos'
    | '/cliente/orcamentos'
    | '/cliente/pagamentos'
    | '/cliente/perfil'
    | '/admin/'
    | '/cliente/'
    | '/admin/clientes/$id'
    | '/admin/clientes/novo'
    | '/admin/contratos/$id'
    | '/admin/eventos/$id'
    | '/admin/eventos/novo'
    | '/admin/orcamentos/$id'
    | '/admin/orcamentos/novo'
    | '/admin/clientes/'
    | '/admin/contratos/'
    | '/admin/eventos/'
    | '/admin/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/agenda'
    | '/admin/atividades'
    | '/admin/configuracoes'
    | '/admin/custos'
    | '/admin/financeiro'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/cliente/contratos'
    | '/cliente/documentos'
    | '/cliente/eventos'
    | '/cliente/orcamentos'
    | '/cliente/pagamentos'
    | '/cliente/perfil'
    | '/admin'
    | '/cliente'
    | '/admin/clientes/$id'
    | '/admin/clientes/novo'
    | '/admin/contratos/$id'
    | '/admin/eventos/$id'
    | '/admin/eventos/novo'
    | '/admin/orcamentos/$id'
    | '/admin/orcamentos/novo'
    | '/admin/clientes'
    | '/admin/contratos'
    | '/admin/eventos'
    | '/admin/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cliente'
    | '/admin/agenda'
    | '/admin/atividades'
    | '/admin/configuracoes'
    | '/admin/custos'
    | '/admin/financeiro'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/cliente/contratos'
    | '/cliente/documentos'
    | '/cliente/eventos'
    | '/cliente/orcamentos'
    | '/cliente/pagamentos'
    | '/cliente/perfil'
    | '/admin/'
    | '/cliente/'
    | '/admin/clientes/$id'
    | '/admin/clientes/novo'
    | '/admin/contratos/$id'
    | '/admin/eventos/$id'
    | '/admin/eventos/novo'
    | '/admin/orcamentos/$id'
    | '/admin/orcamentos/novo'
    | '/admin/clientes/'
    | '/admin/contratos/'
    | '/admin/eventos/'
    | '/admin/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atividades': {
      id: '/admin/atividades'
      path: '/atividades'
      fullPath: '/admin/atividades'
      preLoaderRoute: typeof AdminAtividadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/custos': {
      id: '/admin/custos'
      path: '/custos'
      fullPath: '/admin/custos'
      preLoaderRoute: typeof AdminCustosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/contratos': {
      id: '/cliente/contratos'
      path: '/contratos'
      fullPath: '/cliente/contratos'
      preLoaderRoute: typeof ClienteContratosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/documentos': {
      id: '/cliente/documentos'
      path: '/documentos'
      fullPath: '/cliente/documentos'
      preLoaderRoute: typeof ClienteDocumentosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/eventos': {
      id: '/cliente/eventos'
      path: '/eventos'
      fullPath: '/cliente/eventos'
      preLoaderRoute: typeof ClienteEventosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/orcamentos': {
      id: '/cliente/orcamentos'
      path: '/orcamentos'
      fullPath: '/cliente/orcamentos'
      preLoaderRoute: typeof ClienteOrcamentosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/pagamentos': {
      id: '/cliente/pagamentos'
      path: '/pagamentos'
      fullPath: '/cliente/pagamentos'
      preLoaderRoute: typeof ClientePagamentosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$id': {
      id: '/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/novo': {
      id: '/admin/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/admin/clientes/novo'
      preLoaderRoute: typeof AdminClientesNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/': {
      id: '/admin/contratos/'
      path: '/contratos'
      fullPath: '/admin/contratos/'
      preLoaderRoute: typeof AdminContratosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/$id': {
      id: '/admin/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/admin/contratos/$id'
      preLoaderRoute: typeof AdminContratosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos/': {
      id: '/admin/eventos/'
      path: '/eventos'
      fullPath: '/admin/eventos/'
      preLoaderRoute: typeof AdminEventosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos/$id': {
      id: '/admin/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/admin/eventos/$id'
      preLoaderRoute: typeof AdminEventosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos/novo': {
      id: '/admin/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/admin/eventos/novo'
      preLoaderRoute: typeof AdminEventosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos/': {
      id: '/admin/orcamentos/'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos/'
      preLoaderRoute: typeof AdminOrcamentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos/$id': {
      id: '/admin/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/admin/orcamentos/$id'
      preLoaderRoute: typeof AdminOrcamentosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos/novo': {
      id: '/admin/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/admin/orcamentos/novo'
      preLoaderRoute: typeof AdminOrcamentosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAtividadesRoute: typeof AdminAtividadesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCustosRoute: typeof AdminCustosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesIdRoute: typeof AdminClientesIdRoute
  AdminClientesNovoRoute: typeof AdminClientesNovoRoute
  AdminContratosIdRoute: typeof AdminContratosIdRoute
  AdminEventosIdRoute: typeof AdminEventosIdRoute
  AdminEventosNovoRoute: typeof AdminEventosNovoRoute
  AdminOrcamentosIdRoute: typeof AdminOrcamentosIdRoute
  AdminOrcamentosNovoRoute: typeof AdminOrcamentosNovoRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminContratosIndexRoute: typeof AdminContratosIndexRoute
  AdminEventosIndexRoute: typeof AdminEventosIndexRoute
  AdminOrcamentosIndexRoute: typeof AdminOrcamentosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAtividadesRoute: AdminAtividadesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCustosRoute: AdminCustosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesIdRoute: AdminClientesIdRoute,
  AdminClientesNovoRoute: AdminClientesNovoRoute,
  AdminContratosIdRoute: AdminContratosIdRoute,
  AdminEventosIdRoute: AdminEventosIdRoute,
  AdminEventosNovoRoute: AdminEventosNovoRoute,
  AdminOrcamentosIdRoute: AdminOrcamentosIdRoute,
  AdminOrcamentosNovoRoute: AdminOrcamentosNovoRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminContratosIndexRoute: AdminContratosIndexRoute,
  AdminEventosIndexRoute: AdminEventosIndexRoute,
  AdminOrcamentosIndexRoute: AdminOrcamentosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteRouteChildren {
  ClienteContratosRoute: typeof ClienteContratosRoute
  ClienteDocumentosRoute: typeof ClienteDocumentosRoute
  ClienteEventosRoute: typeof ClienteEventosRoute
  ClienteOrcamentosRoute: typeof ClienteOrcamentosRoute
  ClientePagamentosRoute: typeof ClientePagamentosRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteContratosRoute: ClienteContratosRoute,
  ClienteDocumentosRoute: ClienteDocumentosRoute,
  ClienteEventosRoute: ClienteEventosRoute,
  ClienteOrcamentosRoute: ClienteOrcamentosRoute,
  ClientePagamentosRoute: ClientePagamentosRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
